# Generated by Django 4.2.6 on 2024-01-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('100', '100 Level'), ('200', '200 Level'), ('300', '300 Level'), ('400', '400 Level'), ('ats1', 'ATS 1'), ('ats2', 'ATS 2'), ('ats3', 'ATS 3'), ('skills', 'Skill Level'), ('prof', 'Professional')], default='ats', max_length=10),
        ),
    ]
